// Anonymous independent expectations. No personal workbooks or filename-dependent parser rules.
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm'),root=__dirname,dir=path.join(root,'斯诺德跑团'),ctx={};
vm.createContext(ctx);for(const f of ['character_import_schema.js','character_class_data.js','character_classes.js','character_structure.js','character_layout.js','character_fields.js'])if(fs.existsSync(path.join(dir,f)))vm.runInContext(fs.readFileSync(path.join(dir,f),'utf8'),ctx,{filename:f});
let passed=0,failed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+' '+e.message);}}
const independentExcel=require('xlsx');
const p=(cells,merges=[])=>({sheetName:'匿名角色表',cells,merges,formulas:{}});
test('empty name cannot cross into the species label',()=>{const r=ctx.SNOWD_CHARACTER_FIELDS.read(p({B3:'角色名称',D3:'种族',E3:'人类',K3:'生命值',L3:'80',K4:'疲劳值',L4:'20'}));assert.equal(r.values.name,undefined);assert.equal(r.sources.name.status,'missing');});
test('enemy HP is outside the player binding',()=>{const r=ctx.SNOWD_CHARACTER_FIELDS.read(p({A1:'敌人资料',A2:'生命值',B2:'999',K10:'生命值',L10:'80',K11:'疲劳值',L11:'20'}));assert.equal(r.stats.hp.value,80);assert.equal(r.stats.hp.cellRef,'L10');});
test('conflicting unscoped totals do not select the first value',()=>{const r=ctx.SNOWD_CHARACTER_FIELDS.read(p({A2:'生命值',B2:'999',K10:'生命值',L10:'80'}));assert.equal(r.stats.hp.status,'ambiguous');assert.ok(r.issues.some(i=>i.kind==='field-ambiguous'));});
test('tier capacity is a rule, never a truncation boundary',()=>{const c={B1:'技能列表',B2:'主职业',B3:'技能名称',D3:'施展时间',E3:'施展距离',J3:'效果',B4:'普通能力',D4:'1动作',E4:'6米',J4:'原文',O1:'天赋列表',O2:'一阶天赋树(5)'};for(let r=3;r<=9;r++)c['O'+r]='祝福'+r;const r=ctx.SNOWD_CHARACTER_LAYOUT.readAbilities(p(c,['B1:M1','B2:M2','O1:S1','O2:S2']),[{name:'战士'},{name:''},{name:''}]);assert.equal(r.talents.length,7);assert.ok(r.issues.some(i=>i.kind==='capacity-conflict'));});
test('equipment ability structure survives an unknown item name as a review candidate',()=>{const r=ctx.SNOWD_CHARACTER_LAYOUT.readAbilities(p({U2:'星辰罗盘战术',U3:'星光守护',V3:'原文'}),[]);assert.ok(r.candidates&&r.candidates.some(c=>c.kind==='ability-block'&&c.items.some(e=>e.n==='星光守护')));});


function shifted(cells,dx,dy){const out={};for(const ref in cells){const point=independentExcel.utils.decode_cell(ref);out[independentExcel.utils.encode_cell({c:point.c+dx,r:point.r+dy})]=cells[ref];}return out;}
const golden=Object.freeze({name:'\u767d\u680e',race:'\u4eba\u7c7b',hp:80,fp:20,attrs:Object.freeze({\u529b\u91cf:12,\u654f\u6377:16,\u4f53\u8d28:14,\u667a\u529b:10,\u611f\u77e5:13,\u9b45\u529b:11,\u610f\u5fd7:8,\u5e78\u8fd0:19}),skills:Object.freeze(['\u6298\u5149\u8a93\u8a00','\u661f\u5149\u5b88\u62a4','\u4e91\u53f0\u56de\u65cb'])});
// Renderer vocabulary is fixed here, not imported from recognition dictionaries.
function render(seed){
 const blocks=['identity','combat','classes','attributes','skills'];let x=seed>>>0;const rnd=()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return x>>>0;};
 for(let i=blocks.length-1;i>0;i--){const j=rnd()%(i+1);[blocks[i],blocks[j]]=[blocks[j],blocks[i]];}
 const cells={A1:'\u57fa\u7840\u4fe1\u606f'},merges=[];let row=3;const put=(col,row,value)=>cells[independentExcel.utils.encode_cell({c:col,r:row-1})]=String(value);
 for(const block of blocks){const col=rnd()%5;row+=rnd()%4;
  if(block==='identity'){put(col,row++,'\u57fa\u672c\u4fe1\u606f');[['\u89d2\u8272\u540d\u79f0',golden.name],['\u79cd\u65cf',golden.race]].forEach(([k,v])=>{if(seed%3===0)put(col,row++,k+'\uff1a'+v);else if(seed%3===1){put(col,row++,k);put(col,row++,v);}else{put(col,row,k);put(col+1,row++,v);}});}
  if(block==='combat'){put(col,row++,'\u6218\u6597\u4fe1\u606f');[['\u751f\u547d\u503c',golden.hp],['\u75b2\u52b3\u503c',golden.fp],['\u653b\u51fb\u547d\u4e2d',0],['\u6cd5\u672f\u547d\u4e2d',-2]].forEach(([k,v])=>{put(col,row,k);put(col+1,row++,v);});}
  if(block==='classes'){put(col,row++,'\u804c\u4e1a\u4fe1\u606f');put(col,row,'\u4e3b\u804c\u4e1a');put(col+1,row++,'\u6218\u58eb');put(col,row,'\u4e3b\u804c\u4e1a\u7b49\u7ea7');put(col+1,row++,7);}
  if(block==='attributes'){put(col,row++,'\u5c5e\u6027\u4fe1\u606f');for(const [k,v]of Object.entries(golden.attrs)){put(col,row,k);put(col+1,row++,v);}}
  if(block==='skills'){put(col,row++,'\u6280\u80fd\u5217\u8868');put(col,row++,'\u4e3b\u804c\u4e1a');const head=row++;[['\u6280\u80fd\u540d\u79f0',0],['\u65bd\u5c55\u65f6\u95f4',1],['\u65bd\u5c55\u8ddd\u79bb',2],['\u6301\u7eed\u65f6\u95f4',3],['\u75b2\u52b3\u6d88\u8017',4],['\u6548\u679c',5]].forEach(([k,n])=>put(col+n,head,k));golden.skills.forEach((n,i)=>{put(col,row,n);put(col+1,row,'1\u52a8\u4f5c');put(col+2,row,'6\u7c73');put(col+3,row,'1\u5206\u949f');put(col+4,row,i);put(col+5,row++,n+'\u7684\u5b8c\u6574\u8bf4\u660e');});}
  row+=2;
 }
 const dx=rnd()%35,dy=rnd()%160;return p(shifted(cells,dx,dy),merges);
}
for(let seed=1;seed<=180;seed++)test('unseen semantic layout '+seed,()=>{const input=render(seed),r=ctx.SNOWD_CHARACTER_FIELDS.read(input);assert.equal(r.values.name,golden.name);assert.equal(r.values.race,golden.race);assert.equal(r.stats.hp.value,golden.hp);assert.equal(r.stats.fp.value,golden.fp);assert.deepEqual(JSON.parse(JSON.stringify(r.attrs)),golden.attrs);const abilities=ctx.SNOWD_CHARACTER_LAYOUT.readAbilities(input,[{name:'\u6218\u58eb'},{name:''},{name:''}]);assert.deepEqual(Array.from(abilities.skills,e=>e.n).sort(),golden.skills.slice().sort());});
test('two subjects require a choice; selecting the second has no first-subject data',()=>{const input=p({A1:'\u89d2\u8272\uff1a\u7532',A2:'\u89d2\u8272\u540d\u79f0',B2:'\u7532',A3:'\u751f\u547d\u503c',B3:'70',A20:'\u89d2\u8272\uff1a\u4e59',A21:'\u89d2\u8272\u540d\u79f0',B21:'\u4e59',A22:'\u751f\u547d\u503c',B22:'60'});let r=ctx.SNOWD_CHARACTER_FIELDS.read(input);assert.ok(r.issues.some(i=>i.kind==='entity-unconfirmed'));input.entityId='entity-A20';r=ctx.SNOWD_CHARACTER_FIELDS.read(input);assert.equal(r.values.name,'\u4e59');assert.equal(r.stats.hp.value,60);});
test('ability text resembling a stat is not a stat binding',()=>{const input=p({B1:'\u6280\u80fd\u5217\u8868',B2:'\u4e3b\u804c\u4e1a',B3:'\u6280\u80fd\u540d\u79f0',D3:'\u65bd\u5c55\u65f6\u95f4',E3:'\u65bd\u5c55\u8ddd\u79bb',J3:'\u6548\u679c',B4:'\u751f\u547d\u503c',D4:'1\u52a8\u4f5c',E4:'6\u7c73',J4:'\u5b8c\u6574\u8bf4\u660e',K10:'\u751f\u547d\u503c',L10:'80'},['B1:J1','B2:J2']);assert.equal(ctx.SNOWD_CHARACTER_FIELDS.read(input).stats.hp.value,80);});
test('transposed fields produce the same logical ability parameters',()=>{const input=p({B1:'\u6280\u80fd\u5217\u8868',B2:'\u4e3b\u804c\u4e1a',B3:'\u6280\u80fd\u540d\u79f0',C3:'\u6298\u5149\u8a93\u8a00',D3:'\u661f\u5149\u5b88\u62a4',B4:'\u65bd\u5c55\u65f6\u95f4',C4:'1\u52a8\u4f5c',D4:'\u53cd\u5e94\u52a8\u4f5c',B5:'\u65bd\u5c55\u8ddd\u79bb',C5:'6\u7c73',D5:'\u81ea\u8eab',B6:'\u6301\u7eed\u65f6\u95f4',C6:'1\u5206\u949f',D6:'\u7acb\u5373',B7:'\u75b2\u52b3\u6d88\u8017',C7:'0',D7:'2',B8:'\u6548\u679c',C8:'\u539f\u6587\u7532',D8:'\u539f\u6587\u4e59'},['B1:D1','B2:D2']);const r=ctx.SNOWD_CHARACTER_LAYOUT.readAbilities(input,[{name:'\u6218\u58eb'}]);assert.deepEqual(Array.from(r.skills,e=>e.n),['\u6298\u5149\u8a93\u8a00','\u661f\u5149\u5b88\u62a4']);assert.equal(r.skills[0].dr,'0');assert.equal(r.skills[1].tm,'\u53cd\u5e94\u52a8\u4f5c');assert.equal(r.skills[0].provenance.fields.dr,'C7');});
test('anonymous item headers distinguish quantity and price from weight',()=>{const input=p({A1:'\u57fa\u7840\u4fe1\u606f',I4:'\u88c5\u5907\u680f',I6:'\u80cc\u5305',K6:'\u540d\u79f0',L6:'\u6570\u91cf',M6:'\u4ef7\u683c',N6:'\u6548\u679c',K7:'\u661f\u8fb0\u7f57\u76d8',L7:'3',M7:'120',N7:'\u539f\u6587'});const r=ctx.SNOWD_CHARACTER_FIELDS.read(input),e=r.equipment.\u80cc\u5305[0];assert.equal(e.count,3);assert.equal(e.weightStatus,'unknown');assert.equal(e.weight,0);assert.equal(e.provenance.weightRef,'');});

test('compact companion list ends at blank separation before player progression fields',()=>{const input=p({A1:'\u57fa\u7840\u4fe1\u606f',A2:'\u89d2\u8272\u540d\u79f0',B2:'\u767d\u680e',U4:'\u5ba0\u7269',U5:'\u94f6\u96bc',V5:'\u968f\u884c\u98de\u79bd',U6:'\u5c0f\u72fc',V6:'\u968f\u884c\u517d\u7c7b',U12:'\u76ee\u524d\u7ecf\u9a8c\uff1a2030',U13:'\u76ee\u524d\u6280\u80fd\u70b9\uff1a3'});const r=ctx.SNOWD_CHARACTER_FIELDS.read(input);assert.equal(r.values.xp,2030);assert.equal(r.values.sp_points,3);assert.equal(ctx.SNOWD_CHARACTER_STRUCTURE.analyze(input).owner('U5').owner,'companion');});
test('confirmed binding expires if its label or ownership witness changes',()=>{const input=p({A1:'\u57fa\u7840\u4fe1\u606f',K3:'\u751f\u547d\u503c',L3:'80'});input.fieldBindings=[{field:'hp',sheet:'\u533f\u540d\u89d2\u8272\u8868',cellRef:'L3',confirmed:true,witness:{labelRef:'K3',labelRaw:'\u751f\u547d\u503c',owner:'current'}}];assert.equal(ctx.SNOWD_CHARACTER_FIELDS.read(input).stats.hp.value,80);input.cells.K3='\u4ef7\u683c';const r=ctx.SNOWD_CHARACTER_FIELDS.read(input);assert.equal(r.stats.hp.status,'ambiguous');assert.equal(r.stats.hp.confidence,'stale-confirmation');});
console.log('General import: '+passed+'P '+failed+'F');if(failed)process.exitCode=1;

(async function browserChecks(){
 const {chromium,_electron}=require('playwright'),X=require('xlsx'),os=require('os'),{pathToFileURL}=require('url');let browser,electron;
 async function check(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+'\n'+e.stack);}}
 function bytes(parsed){const b=X.utils.book_new(),sh={};for(const r in parsed.cells)sh[r]={t:'s',v:parsed.cells[r]};sh['!ref']=X.utils.encode_range({s:{r:0,c:0},e:{r:Math.max(...Object.keys(parsed.cells).map(r=>X.utils.decode_cell(r).r)),c:Math.max(...Object.keys(parsed.cells).map(r=>X.utils.decode_cell(r).c))}});sh['!merges']=(parsed.merges||[]).map(X.utils.decode_range);X.utils.book_append_sheet(b,sh,'匿名角色');return X.write(b,{type:'buffer',bookType:'xlsx',bookSST:true,compression:true});}
 async function imported(page,buf){return page.evaluate(async b64=>{await ensureSkillDataForExport();const p=await parseXLSX(Uint8Array.from(atob(b64),c=>c.charCodeAt(0)).buffer),s=buildState(p);autoCorrect(s);return s;},buf.toString('base64'));}
 async function exported(page,s,buf){return Buffer.from(await page.evaluate(async({s,b})=>{state=s;if(b)state._uploadedXlsxBuf=Uint8Array.from(atob(b),c=>c.charCodeAt(0)).buffer;await exportXlsxFromState(state);const a=new Uint8Array(await __generalBlobs.at(-1).arrayBuffer());let raw='';for(const n of a)raw+=String.fromCharCode(n);return btoa(raw);},{s,b:buf&&buf.toString('base64')}),'base64');}
 function capture(){window.__generalBlobs=[];URL.createObjectURL=b=>{__generalBlobs.push(b);return 'blob:general';};HTMLAnchorElement.prototype.click=function(){};}
 try{
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>r.request().url().startsWith('file:')?r.continue():r.abort());await context.addInitScript(capture);const upload=await context.newPage(),panel=await context.newPage(),errors=[];for(const page of [upload,panel])page.on('pageerror',e=>errors.push(e.message));await upload.goto(pathToFileURL(path.join(dir,'上传角色.html')).href,{waitUntil:'load'});await panel.goto(pathToFileURL(path.join(dir,'角色面板.html')).href,{waitUntil:'load'});
  const input=render(101),buf=bytes(input),base=await imported(upload,buf);
  await check('structural import has no template default contamination',async()=>{assert.equal(base.importAdapter,'structural');assert.equal(base.name,golden.name);assert.deepEqual(base.attrs,golden.attrs);assert.equal(base.classes[0].name,'战士');assert.equal(base.classes[0].level,7);assert.equal(base.hp,80);assert.equal(base.fp,20);assert.deepEqual(base.skills.map(e=>e.n).sort(),golden.skills.slice().sort());});
  await check('changing a field source through UI resolves an ambiguity and roundtrips',async()=>{
   const conflicting=structuredClone(input);conflicting.cells.ZZ200='生命值';conflicting.cells.AAA200='999';const source=bytes(conflicting),s=await imported(upload,source);assert.equal(s.fieldSources.scalar.hp.status,'ambiguous');await upload.evaluate(s=>{pendingState=s;openFieldBindingResolver(s);},s);
   const d=upload.locator('#characterIssueDialog');await d.getByLabel('要绑定的字段',{exact:true}).selectOption('hp');const hpRef=base.fieldSources.scalar.hp.cellRef;await d.getByLabel('原始值单元格',{exact:true}).fill(hpRef);await d.getByRole('button',{name:'加入字段绑定',exact:true}).click();await d.getByRole('button',{name:'确认范围与字段',exact:true}).click();const fixed=await upload.evaluate(()=>pendingState);assert.equal(fixed.hp,80);const again=await imported(upload,await exported(panel,fixed,source));assert.equal(again.hp,80);assert.ok(again.importFieldBindings.some(b=>b.field==='hp'&&b.cellRef===hpRef));
  });
  await check('transposed table writer preserves cells, logical fields and UID',async()=>{
   const transposed=structuredClone(input);const grid=ctx.SNOWD_CHARACTER_LAYOUT.grid(transposed),skills=ctx.SNOWD_CHARACTER_LAYOUT.detect(transposed).skills[0];
   for(const r of Object.keys(transposed.cells)){const point=ctx.SNOWD_CHARACTER_LAYOUT.point(r);if(point.row>=skills.row&&point.row<skills.end&&point.col>=skills.nameCol&&point.col<=skills.right)delete transposed.cells[r];}
   Object.assign(transposed.cells,{AD220:'技能列表',AD221:'主职业',AD222:'技能名称',AE222:'折光誓言',AF222:'星光守护',AD223:'施展时间',AE223:'1动作',AF223:'反应动作',AD224:'施展距离',AE224:'6米',AF224:'自身',AD225:'持续时间',AE225:'1分钟',AF225:'立即',AD226:'疲劳消耗',AE226:'0',AF226:'2',AD227:'效果',AE227:'原文甲',AF227:'原文乙'});transposed.merges.push('AD220:AF220','AD221:AF221');const source=bytes(transposed),s=await imported(upload,source),ids=s.skills.map(e=>e.uid).sort();assert.equal(s.skills.length,2);const output=await exported(panel,s,source),b=X.read(output,{type:'buffer'});assert.equal(b.Sheets.匿名角色.AE226.v,'0');assert.equal(b.Sheets.匿名角色.AF223.v,'反应动作');const r=await imported(upload,output);assert.deepEqual(r.skills.map(e=>e.uid).sort(),ids);
  });
  await check('metadata species/background references expire when visible identity text changes',async()=>{
   const s=structuredClone(base);s.ruleRace='人类';const output=X.read(await exported(panel,s,buf),{type:'buffer'}),ref=s.fieldSources.scalar.race.cellRef;output.Sheets.匿名角色[ref]={t:'s',v:'矮人'};const changed=X.write(output,{type:'buffer',bookType:'xlsx',bookSST:true,compression:true}),r=await imported(upload,changed);assert.equal(r.race,'矮人');assert.equal(r.ruleRace,'');assert.ok(r.importIssues.some(i=>i.kind==='confirmation-stale'));
  });
  await check('unknown names in an undeclared equipment list remain raw candidates',async()=>{
   const raw=structuredClone(input);Object.assign(raw.cells,{ZZ250:'星辰罗盘战术',ZZ251:'星光守护',AAA251:'主持人提供的完整原文'});const s=await imported(upload,bytes(raw));assert.ok(s.importCandidates.some(c=>c.kind==='ability-block'&&c.items.some(e=>e.n==='星光守护')));assert.equal(s.skills.length,3);
  });
  await check('same-name rows reordered match metadata by distinct visible content',async()=>{
   const s=structuredClone(base);s.skills[0].n=s.skills[1].n='同名能力';s.skills[0].ds='原文甲';s.skills[1].ds='原文乙';s.skills[0].resolution=s.skills[1].resolution='custom';s.skills[0].selectedOptions={pick:'甲'};s.skills[1].selectedOptions={pick:'乙'};const output=X.read(await exported(panel,s,buf),{type:'buffer'}),sh=output.Sheets.匿名角色;
   const rows=[s.skills[0].cellRef,s.skills[1].cellRef].map(r=>Number(r.replace(/[A-Z]/g,''))),cols=Object.values(s.skills[0]._writtenFields||{}).map(r=>r.replace(/\d/g,''));if(!cols.length)for(const key in sh){if(key.startsWith('!'))continue;const point=X.utils.decode_cell(key);if(rows.includes(point.r+1)&&!cols.includes(X.utils.encode_col(point.c)))cols.push(X.utils.encode_col(point.c));}
   for(const col of cols){const a=col+rows[0],b=col+rows[1],[x,y]=[sh[a],sh[b]];sh[a]=y;sh[b]=x;}const r=await imported(upload,X.write(output,{type:'buffer',bookType:'xlsx',bookSST:true,compression:true}));assert.deepEqual(r.skills.find(e=>e.ds==='原文甲').selectedOptions,{pick:'甲'});assert.deepEqual(r.skills.find(e=>e.ds==='原文乙').selectedOptions,{pick:'乙'});
  });
  await check('unreviewed text is visible in cache-free export',async()=>{const s=structuredClone(base);s.importUnreviewed.push({cellRef:'ZZ299',raw:'不得丢失的独立原文',sheet:'匿名角色'});const b=X.read(await exported(panel,s),{type:'buffer'});assert.ok(Object.values(b.Sheets[b.SheetNames.find(n=>n!=='_SNODE_META')]).some(c=>c&&c.v==='不得丢失的独立原文'));});
  await check('variable cost is per-use and leaves the imported rule unchanged',async()=>{
   const result=await panel.evaluate(s=>{state=s;state.skills[0].dr='X';state.skills[0].cost='X';state.skills[0].resolution='custom';SB_reinit();S.battle=true;S.fp=20;var called=0;var original=SD_prompt;SD_prompt=function(options,done){called++;done('3');};useSkill(state.skills[0].n,state.skills[0].uid);SD_prompt=original;return {fp:S.fp,raw:state.skills[0].dr,called};},structuredClone(base));assert.equal(result.fp,17);assert.equal(result.raw,'X');assert.equal(result.called,1);
  });
  await check('review workbench and equipment mapping fit all required viewports',async()=>{for(const width of [360,390,1440]){await panel.setViewportSize({width,height:900});for(const fn of ['openFieldBindingResolver','equipment']){await panel.evaluate(async({s,fn,b})=>{state=s;state._uploadedXlsxBuf=Uint8Array.from(atob(b),c=>c.charCodeAt(0)).buffer;if(fn==='equipment')await SNOWD_CHARACTER_REVIEW.equipment(state);else await openFieldBindingResolver(state);},{s:base,fn,b:buf.toString('base64')});const r=await panel.locator('#characterIssueDialog section').evaluate(e=>({l:e.getBoundingClientRect().left,r:e.getBoundingClientRect().right,w:innerWidth,s:e.scrollWidth,c:e.clientWidth}));assert.ok(r.l>=0&&r.r<=r.w+1&&r.s<=r.c+1);await panel.keyboard.press('Escape');}}});
  await check('equipment mapping imports unfamiliar columns without converting price to weight',async()=>{
   const input2=structuredClone(input);Object.assign(input2.cells,{AB240:'未知清单',AC241:'陌生物件',AD241:'完整说明',AE241:'4',AF241:'6',AG241:'999'});const source=bytes(input2),s=await imported(upload,source);await upload.evaluate(async s=>{pendingState=s;await SNOWD_CHARACTER_REVIEW.equipment(s);},s);
   const d=upload.locator('#characterIssueDialog');await d.getByLabel('装备数据范围',{exact:true}).fill('AC241:AG241');await d.getByLabel('原装备分区',{exact:true}).fill('背包');await d.getByLabel('物品名称列',{exact:true}).fill('AC');await d.getByLabel('物品说明列',{exact:true}).fill('AD');await d.getByLabel('数量列',{exact:true}).fill('AE');await d.getByLabel('重量列',{exact:true}).fill('AF');await d.getByRole('button',{name:'确认装备映射',exact:true}).click();const result=await upload.evaluate(()=>pendingState),item=result.equipment.背包.find(e=>e.item==='陌生物件');assert.ok(item);assert.equal(item.weight,6);assert.equal(item.count,4);item.count=5;const r=await imported(upload,await exported(panel,result,source));assert.ok(r.equipment.背包.some(e=>e.item==='陌生物件'&&e.weight===6&&e.count===5));
  });
  await check('actual one-time-cost dialog accepts zero or a positive value and retains X',async()=>{
   await panel.evaluate(s=>{state=s;state.skills[0].dr='X';state.skills[0].cost='X';state.skills[0].resolution='custom';SB_reinit();S.battle=true;S.fp=20;useSkill(state.skills[0].n,state.skills[0].uid);},structuredClone(base));
   const input=panel.locator('input[type="number"]:visible').last();await input.fill('3');await panel.getByRole('button',{name:'确定',exact:true}).last().click();const r=await panel.evaluate(()=>({fp:S.fp,raw:state.skills[0].dr}));assert.equal(r.fp,17);assert.equal(r.raw,'X');
  });
  await check('held-out synthetic layouts are read without template recognition',async()=>{for(const seed of [18001,18007,18011,18023,18037,18059]){const s=await imported(upload,bytes(render(seed)));assert.equal(s.name,golden.name);assert.deepEqual(s.attrs,golden.attrs);assert.equal(s.hp,80);assert.deepEqual(s.skills.map(e=>e.n).sort(),golden.skills.slice().sort());}});
  await check('no renderer errors',async()=>assert.deepEqual(errors,[]));await browser.close();browser=null;
  if(process.argv.includes('--electron')){
   const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'general-import-electron-')),profile=path.join(tmp,'profile'),boot=path.join(tmp,'boot.cjs');fs.mkdirSync(profile);fs.writeFileSync(boot,"const {app,BrowserWindow}=require('electron');app.disableHardwareAcceleration();app.setPath('userData',"+JSON.stringify(profile)+");app.setPath('sessionData',"+JSON.stringify(profile)+");app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1440,height:900,webPreferences:{contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});w.loadURL('about:blank');});app.on('window-all-closed',()=>app.quit());");
   try{electron=await _electron.launch({executablePath:require('./electron-app/node_modules/electron'),args:[boot]});const page=await electron.firstWindow();await page.route('**/*',r=>r.request().url().startsWith('file:')?r.continue():r.abort());await page.addInitScript(capture);await page.goto(pathToFileURL(path.join(dir,'角色面板.html')).href,{waitUntil:'load'});
    await check('Electron review source binding and export',async()=>{await page.evaluate(async({s,b})=>{state=s;state._uploadedXlsxBuf=Uint8Array.from(atob(b),c=>c.charCodeAt(0)).buffer;await openFieldBindingResolver(state);},{s:base,b:buf.toString('base64')});assert.ok(await page.locator('#characterIssueDialog').count());await page.keyboard.press('Escape');assert.ok(X.read(await exported(page,base,buf),{type:'buffer'}).Sheets._SNODE_META);});
   }finally{if(electron){await electron.close();electron=null;}const target=path.resolve(tmp);assert.ok(target.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(target).startsWith('general-import-electron-'));fs.rmSync(target,{recursive:true,force:true,maxRetries:3});}
  }
 }catch(e){failed++;console.error(e.stack);}finally{if(browser)await browser.close();if(electron)await electron.close();}
 console.log('General import total: '+passed+'P '+failed+'F');process.exitCode=failed?1:0;
})();
