import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),data=path.join(root,'职业页','数据');
const grouped=new Map();
for(const name of fs.readdirSync(data).filter(n=>n.endsWith('·进阶.json'))){
 const json=JSON.parse(fs.readFileSync(path.join(data,name),'utf8'));
 for(const a of json.advancements||[]){
  if(!a.name)continue;const old=grouped.get(a.name)||{name:a.name,ids:[],source_classes:[],conditions:[],attrs:{},cost:[]};
  if(a.id&&!old.ids.includes(a.id))old.ids.push(a.id);
  for(const n of a.source_classes||[])if(!old.source_classes.includes(n))old.source_classes.push(n);
  for(const c of a.conditions||[])if(!old.conditions.includes(c))old.conditions.push(c);
  old.attrs=a.attrs||old.attrs;old.cost=a.cost||old.cost;grouped.set(a.name,old);
 }
}
const base=['召唤师','吟游诗人','圣骑士','奇械师','守望者','德鲁伊','战士','战舞者','术士','武僧','法师','游荡者','牧师','猎人','萨满祭司','蛮斗士','谋士','魔契师'];
const content='/* Generated by scripts/build_character_class_registry.mjs. */\nvar SNOWD_CHARACTER_CLASS_DATA='+JSON.stringify({schemaVersion:1,base,advancements:[...grouped.values()].sort((a,b)=>a.name.localeCompare(b.name))})+';\n';
for(const dir of ['斯诺德跑团','electron-app/斯诺德跑团'])fs.writeFileSync(path.join(root,dir,'character_class_data.js'),content,'utf8');
console.log('Class registry: '+base.length+' base / '+grouped.size+' advancement names');
